### ISSUE TITLE
URLs need better formatting

### ISSUE THREAD

**Issue by InteropAdmin** [nhsconnect/CareConnectAPI#12]
is there a better way to format the page so the URLs do not wrap around the table columns?

**Comment by KevinMayfield** [comment]
Yes, we should move them to over to html tables rather than jekyll markdown tables.

**Comment by KevinMayfield** [comment]
https://care-connect-api.netlify.com/support_referenceapiservers.html

This is the page with the wrapping issue

**Comment by markodukic** [comment]
Corrected wrapping by moving to html tables
