### ISSUE TITLE
Links from Implementation Guide to Reference server not working

### ISSUE THREAD

**Issue by KevinMayfield** [nhsconnect/CareConnectAPI#14]
Click on a link from a resource page 
e.g. https://nhsconnect.github.io/CareConnectAPI/api_medication_medicationstatement.html

The call fails with Warning!
Error: HTTP 415 Unsupported Media Type: Unsupported media type: mime json

This isn't a valid mime type, server only supports valid mime types (e.g. application/json)

**Comment by Dunmail** [comment]
It's also pointing to a test server, rather than the production instance ...

**Comment by KevinMayfield** [comment]
Several issues:
1. thymeleaf javascript was using xml and json parameters, not full mime reference
2. thymeleaf java code is using xml and json (this is core hapi https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-testpage-overlay/src/main/java/ca/uhn/fhir/to/model/HomeRequest.java)
3. (this.)jekyll pages need updating to using correct parameter

**Comment by KevinMayfield** [comment]
One solution is to remove option from UI. _format command works fine on the server, this is just a UI issue.

**Comment by KevinMayfield** [comment]
logged on jira

**Comment by KevinMayfield** [comment]
Fixed on development environment. ccri altered to stop rejecting xml and json as invalid mime types.

Awaiting release.
