### ISSUE TITLE
ECL syntax errors - sequence of MINUS operators

### ISSUE THREAD

**Issue by lawley** [nhsconnect/CareConnectAPI#16]
The ECL in `CareConnect-Condition-1.xml` contains syntax error where it expresses a set of exclusions.  In particular, the following constraint is syntactically incorrect as only a simple subExpression or a bracketed complex expression can follow the keyword `MINUS`:

`< 243796009 |Situation with explicit context|: 246090004 |Associated finding| = ((< 404684003 |Clinical finding| MINUS << 420134006 |Propensity to adverse reactions| MINUS << 473010000 |Hypersensitivity condition| MINUS << 79899007 |Drug interaction| MINUS << 69449002 |Drug action| MINUS << 441742003 |Evaluation finding| MINUS << 307824009 |Administrative status| MINUS << 385356007 |Tumor stage finding|) OR < 272379006 |Event|)`

The better way to write this would be:

`< 243796009 |Situation with explicit context| : 246090004 |Associated finding| = ( ( < 404684003 |Clinical finding| MINUS ( << 420134006 |Propensity to adverse reactions| OR << 473010000 |Hypersensitivity condition| OR << 79899007 |Drug interaction| OR << 69449002 |Drug action| OR << 441742003 |Evaluation finding| OR << 307824009 |Administrative status| OR << 385356007 |Tumor stage finding|)) OR < 272379006 |Event|) `

Results can be seen [here](http://ontoserver.csiro.au/shrimp/ecl.html?q=<%20243796009%20|Situation%20with%20explicit%20context|%20:%20246090004%20|Associated%20finding|%20=%20(%20(%20<%20404684003%20|Clinical%20finding|%20MINUS%20(%20<<%20420134006%20|Propensity%20to%20adverse%20reactions|%20OR%20<<%20473010000%20|Hypersensitivity%20condition|%20OR%20<<%2079899007%20|Drug%20interaction|%20OR%20<<%2069449002%20|Drug%20action|%20OR%20<<%20441742003%20|Evaluation%20finding|%20OR%20<<%20307824009%20|Administrative%20status|%20OR%20<<%20385356007%20|Tumor%20stage%20finding|))%20OR%20<%20272379006%20|Event|))

**Comment by InteropAdmin** [comment]
@lawley looking closer at the issue you reported it appears that the ECL issue you have picked up is with the base FHIR resource. Take a look here http://hl7.org/fhir/STU3/condition-mappings.html 

We can raise an issue with this but it would be more helpful if you can do that directly yourself as you'd have the details on the technicalities of the ECL issue.

**Comment by lawley** [comment]
Thanks, I missed that.  Will raise it on the FHIR tracker.
