### ISSUE TITLE
About ccri-document-server

### ISSUE THREAD

**Issue by developerworks** [nhsconnect/CareConnectAPI#26]
Where is the `careconnect-document` of the `6. Next Steps` in web page: https://nhsconnect.github.io/CareConnectAPI/build_patient_server.html

**Comment by developerworks** [comment]
The link is broken.
https://github.com/nhsconnect/careconnect-document/tree/master/ccri-document-server

**Comment by KevinMayfield** [comment]
The NHSD version: 
This doesn't have subprojects anymore
https://github.com/nhsconnect/careconnect-document 

A newer version is here
https://github.com/project-wildfyre/document-repository
