### ISSUE TITLE
CareConnect Observation - Read Operation

### ISSUE THREAD

**Issue by KevinMayfield** [nhsconnect/CareConnectAPI#5]
SK - I know ‘operation’ is technically correct but FHIR tends to refer to these as ‘interactions’ i.e. to avoid confusion with rpc calls

**Comment by KevinMayfield** [comment]
I think this page which is REST focused should following CRUD. So Create, Read, Update, Delete and Search. 

So I would be happy to loose the word Operation. Is that ok

**Comment by swk003** [comment]
I think we try and stick as close to the FHIR standard as we can - certainly at this stage. So happy for CRUD definitions.
