### ISSUE TITLE
Observation - GET /Observation?_id=[id]

### ISSUE THREAD

**Issue by KevinMayfield** [nhsconnect/CareConnectAPI#6]
SK - search param. Returns a bundle of type searchset and not an instance of observation. This works, I’m not quite sure why it would be used.

**Comment by KevinMayfield** [comment]
This is correct FHIR behaviour.

**Comment by swk003** [comment]
I get that it is valid FHIR. We are mixing up READ and SEARCH interactions (within the READ Interaction section). So my Q is what are the advantages of this approach?

**Comment by KevinMayfield** [comment]
Ok, I get what you mean so you mean remove this from the READ section 

GET /Observation?_id=[id]

**Comment by swk003** [comment]
GET /Observation/[id] returns and instance of observation
GET /Observation?_id=[id] returns a bundle

So would a client sys prefer the instance or bundle with contained instance. I'm guessing the former but I dont know for sure.
