### ISSUE TITLE
Observation -Search Parameters

### ISSUE THREAD

**Issue by KevinMayfield** [nhsconnect/CareConnectAPI#7]
SK - Optional DSTU2 search params include some of the SHOULD implement params. I think perhaps we highlight the fact that DSTU2 ‘supports’ a wider range of search params..of which CC provider sys should as a minimum support the table of params
Recommended  col – I am not sure I get this?
Patient:
To avoid confusion the Patient param sections should be renamed to reflect searching using ‘logical id’ and search using ‘business ID’ .
:systemUri is a uniform resource identifier – do we need to explicitly state what a URI is? I get the message, but again I think local creation of URIs should stay generic to the API spec
patient.identifier={systemUri}|[identifier] – this is a chained search

**Comment by KevinMayfield** [comment]
I think we need a separate page for things like systemUri which would explain what it is. We should go into detailed discussions of common behaviour.

**Comment by KevinMayfield** [comment]
This is in Design and Build -> Build -> Patient Search

**Comment by swk003** [comment]
I think this issue will be covered off with conformance definition. I haven't goner through patient search yet with fine tooth comb but could see anything specific that points to this issue.
