### ISSUE TITLE
Observation - Code Section Query on a list of codes (ValueSet) or code hierarchy 

### ISSUE THREAD

**Issue by KevinMayfield** [nhsconnect/CareConnectAPI#8]
SK 

Code:
code={systemUri}|[code] – empty section??

To search for all resources with ‘Body composition measure’ codes using SNOMED CT – I tried this and couldn’t get the expected result. Can we discuss?
Date search type example uses prefixes – perhaps we could indicate in description

**Comment by KevinMayfield** [comment]
Where did you try the query? The code 846931000000101 (http://www.snomedbrowser.com/Codes/Details/846931000000101) It's a UK SNOMED code which may be the issue

**Comment by swk003** [comment]
I was struggling with the modifier example query

**Comment by KevinMayfield** [comment]
So GET /Observation?code:below=http://snomed.info/sct|363810004

I was wondering about that one. It was supported on primary care EPR's in the 90's (for READ codes). Personally I think this kind of query to search on a list of codes SHALL be available but how it is done is up for comment. It could be done by putting all the codes into a ValueSet (and pass the ValueSet as a parameter) or the client lists all the codes (and subcodes) in the query.

**Comment by KevinMayfield** [comment]
Removed modifiers from Observation search params

**Comment by swk003** [comment]
Checking between versions 0.4.0 and 0.5.0 i couldn't work out which modifiers were removed??

**Comment by KevinMayfield** [comment]
It was removed between 1 and 2. I suggested we should search using modifiers but following discussions it was removed
